version: '3.9'
services:
  bot:
    image: bot
    container_name: bot-local
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000'
    volumes:
      - ./db:/usr/src/db
    env_file:
      - .env
