version: '3.9'
services:
  bot:
    image: bot
    container_name: bot-local
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./prisma/data:/data
      - $PNPM_STORE:/root/.local/share/pnpm/store/v3
    env_file:
      - .env
    environment:
      - DATABASE_URL=file:/data/local.db
