name: New Command
description: Request a new Discord slash command
title: 'command: '
labels: ['needs: triage', 'category: command']

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this request!
  - type: input
    id: name
    attributes:
      label: Name of the command
      description: 'For example: giverole, ping'
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the Command's Usage
      description: 'Describe the command you would like to see including sampel usage, tentative designs, expectations, etc.'
    validations:
      required: true
