# used to extract the version from a release branch
# "release/1.0.0-next.0" -> "1.0.0-next.0"
name: cleanup-discarded-release
description: Cleans up discarded release artifacts such as branch and draft release
inputs:
  github-token:
    description: GitHub token needed for ops
    default: ${{ github.token }}
    required: true
  version:
    description: version of the discarded release (e.g. v1.0.0-next.0)
    required: true
  branch:
    description: branch name (e.g. head_ref)
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: true
    - name: delete-release-branch
      run: git push origin --quiet --delete ${{ inputs.branch }} && echo 'deleted branch' || true
      shell: bash
    - name: delete-release-draft
      run: gh release delete ${{ inputs.version }} && echo 'deleted release' || true
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
