#!/bin/sh

function publish () {
  pnpm publish --registry http://localhost:4000 --no-git-checks $1
}

# if jq does not exist, attempt install
if ! [ -x "$(command -v jq)" ]
then
  # installation is intended for Amplify Hosting pipeline
  yum install jq -y
fi

# workaround for Amplify Hosting pipeline, adds "packaged-node-modules" to ~/.amplify/plugins.json
function write_to_plugins () {
  node scripts/patch.js
}

# start_verdaccio
pnpm verdaccio --listen 4000 --config ./scripts/verdaccio.yaml &
VERDACCIO_PID=$!
# wait for verdaccio layer to start
while ! curl --output /dev/null --silent --head --fail http://localhost:4000
do 
  sleep 1
done
echo "Verdaccio layer started! 🚀"

# iterate over workspace packages to publish
for PACKAGE in $(find ~+/packages -mindepth 1 -maxdepth 1 -type d)
do
  PACKAGE_NAME=$(jq '.name' -r $PACKAGE/package.json)
  PACKAGE_VERSION=$(jq '.version' -r $PACKAGE/package.json)
  PACKAGE_BUILD_COMMAND=$(jq '.scripts.build' -r $PACKAGE/package.json)
  PACKAGE_IS_PRIVATE=$(jq '.private' -r $PACKAGE/package.json)


  if [ $PACKAGE_IS_PRIVATE != true ] 
  then
    echo "Publishing $PACKAGE_NAME@$PACKAGE_VERSION"
    # publish workspace package to verdaccio
    publish $PACKAGE
  fi
done


# push resources (should install lambda deps from verdaccio)
echo "Running amplify push..."
HELPER_BACKEND_BUILD_EXIT_CODE=0
# check if we're running in Amplify Console, where helper scripts should be available
if [ -x "$(command -v amplifyPush)" ]
then
  echo 'amplifyPush helper script detected!'
  write_to_plugins
  amplifyPush --simple
  HELPER_BACKEND_BUILD_EXIT_CODE=$?
else
  echo 'no amplifyPush script found'
  # if not in Amplify Console (local) run from Amplify CLI directly
  amplify push -y
fi


# kill verdaccio, remove storage
echo "Stopping Verdaccio..."
kill $VERDACCIO_PID
echo "Done! 🙌"

if [ $HELPER_BACKEND_BUILD_EXIT_CODE -ne 0 ]; then
  echo "Oh no 🤕"
fi
exit $HELPER_BACKEND_BUILD_EXIT_CODE