name: issue-pending-response
on:
  issue_comment:
    types: [created]
env:
  PENDING_RESPONSE_LABEL: 'pending: author'
jobs:
  issue_commented:
    runs-on: ubuntu-latest
    if: |
      !github.event.issue.pull_request && 
      contains(github.event.issue.labels.*.name, 'pending: author')
    steps:
      - uses: siegerts/pending-author-response@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pending-response-label: ${{ env.PENDING_RESPONSE_LABEL }}
