name: release
on:
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  verify-run:
    runs-on: ubuntu-latest
    # We run release action only if:
    #   1. PR comes from internal branch (i.e. not a fork)
    #   2. PR is merged (a PR can be closed but not merged)
    #   3. PR branch name begins with "release/"
    if: |
      github.event.pull_request.head.repo.full_name == github.repository &&
      github.event.pull_request.merged == true && 
      startsWith(github.event.pull_request.head.ref, 'release/')
    outputs:
      version: ${{ steps.extract-version.outputs.version }}
      is-prerelease: ${{ contains(steps.extract-version.outputs.version, 'next') }}
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - id: extract-version
        uses: ./.github/actions/extract-version-from-branch
        with:
          branch: ${{ github.head_ref }}
  prerelease:
    needs: verify-run
    uses: ./.github/workflows/release-env.yaml
    secrets: inherit
    with:
      env: next
      version: ${{ needs.verify-run.outputs.version }}
      is-prerelease: true
  release:
    needs: [verify-run, prerelease]
    if: ${{ fromJSON(needs.verify-run.outputs.is-prerelease) == false }}
    uses: ./.github/workflows/release-env.yaml
    secrets: inherit
    with:
      env: main
      version: ${{ needs.verify-run.outputs.version }}
      is-prerelease: false
